version: '3'
services:
 web:
    image: json1/dmugnginx
    container_name: nginxdmug
    restart: unless-stopped
    ports:
        - "8080:80"
    volumes:
        - ./www:/var/www
       
    links:
        - php
    networks:
      - dmug
    restart: always
    depends_on:
      - php
 php:
    image: json1/dmugphp
    container_name: phpdmug
    restart: unless-stopped
    volumes:
        - ./www:/var/www
    networks:
      - dmug

networks:
  dmug:
  
